build:
  stage: build
  script:
    - echo $DOCKER_REPO_PASSWORD | docker login --username=$DOCKER_REPO_USERNAME --password-stdin $DOCKER_REPO_URL
    - docker build . -f Dockerfile_8-extracted -t $DOCKER_REPO_URL/fdboot:8-extracted && docker push $DOCKER_REPO_URL/fdboot:8-extracted
    - docker build . -f Dockerfile_8-extracted-openj9 -t $DOCKER_REPO_URL/fdboot:8-extracted-openj9 && docker push $DOCKER_REPO_URL/fdboot:8-extracted-openj9
    - docker build . -f Dockerfile_8-fatjar -t $DOCKER_REPO_URL/fdboot:8-fatjar && docker push $DOCKER_REPO_URL/fdboot:8-fatjar
    - docker build . -f Dockerfile_8-fatjar-openj9 -t $DOCKER_REPO_URL/fdboot:8-fatjar-openj9 && docker push $DOCKER_REPO_URL/fdboot:8-fatjar-openj9

    - docker build . -f Dockerfile_11-extracted -t $DOCKER_REPO_URL/fdboot:11-extracted && docker push $DOCKER_REPO_URL/fdboot:11-extracted
    - docker build . -f Dockerfile_11-extracted-openj9 -t $DOCKER_REPO_URL/fdboot:11-extracted-openj9 && docker push $DOCKER_REPO_URL/fdboot:11-extracted-openj9
    - docker build . -f Dockerfile_11-fatjar -t $DOCKER_REPO_URL/fdboot:11-fatjar && docker push $DOCKER_REPO_URL/fdboot:11-fatjar
    - docker build . -f Dockerfile_11-fatjar-openj9 -t $DOCKER_REPO_URL/fdboot:11-fatjar-openj9 && docker push $DOCKER_REPO_URL/fdboot:11-fatjar-openj9

    - docker tag $DOCKER_REPO_URL/fdboot:8-fatjar $DOCKER_REPO_URL/fdboot && docker push $DOCKER_REPO_URL/fdboot
    - docker tag $DOCKER_REPO_URL/fdboot:8-fatjar $DOCKER_REPO_URL/fdboot:fatjar && docker push $DOCKER_REPO_URL/fdboot:fatjar
    - docker tag $DOCKER_REPO_URL/fdboot:8-extracted $DOCKER_REPO_URL/fdboot:extracted && docker push $DOCKER_REPO_URL/fdboot:extracted
