FROM adoptopenjdk:11-jdk


RUN sed -i 's/archive\.ubuntu\.com/mirrors\.aliyun\.com/g' /etc/apt/sources.list &&\
    sed -i 's/security\.ubuntu\.com/mirrors\.aliyun\.com/g' /etc/apt/sources.list &&\
    apt-get update &&\
    apt-get install -y curl lrzsz vim telnet locales iproute2 language-pack-zh-hans fonts-wqy-zenhei &&\
    localedef -c -f UTF-8 -i zh_CN zh_CN.utf8 &&\
    apt-get clean

ENV SERVER_TOMCAT_MAX_THREADS=50 \
        EUREKA_INSTANCE_PREFER_IP_ADDRESS=true \
        JAVA_MEM_OPTS="-Xmx500m " \
        JAVA_GC_OPTS="" \
        TZ=Asia/Shanghai \
        LANG=zh_CN.utf8 


WORKDIR /app

COPY extracted/* common/* ./
COPY jdk11/java.security /opt/java/openjdk/jre/lib/security/java.security

VOLUME /var/log/fdserver

CMD [ "./boot.sh" ]

HEALTHCHECK --interval=2s --timeout=60s --start-period=10s --retries=3 CMD [ "./health-check.sh" ]
