FROM openjdk:11-jdk


RUN apt-get update &&\
    apt-get install -y curl lrzsz vim telnet locales iproute2 

ENV SERVER_TOMCAT_MAX_THREADS=50 \
        EUREKA_INSTANCE_PREFER_IP_ADDRESS=true \
        JAVA_MEM_OPTS="-Xmx500m " \
        JAVA_GC_OPTS=" " \
        TZ=Asia/Shanghai 


WORKDIR /app

COPY fatjar/* common/* ./
COPY jdk11/java.security /usr/local/openjdk-11/conf/security/java.security

VOLUME /var/log/fdserver

CMD [ "./boot.sh" ]

HEALTHCHECK --interval=2s --timeout=60s --start-period=10s --retries=3 CMD [ "./health-check.sh" ]
