FROM  adoptopenjdk:8-jdk-openj9

RUN apt-get update &&\
    apt-get install -y curl lrzsz vim telnet locales iproute2 wqy-* &&\
    localedef -c -f UTF-8 -i zh_CN zh_CN.utf8 &&\
    apt-get clean

ENV SERVER_TOMCAT_MAX_THREADS=50 \
        EUREKA_INSTANCE_PREFER_IP_ADDRESS=true \
        JAVA_MEM_OPTS="-Xmx500m " \
        JAVA_GC_OPTS="-XX:+UseG1GC " \
        TZ=Asia/Shanghai \
        LANG=zh_CN.utf8 


WORKDIR /app

COPY fatjar/* common/* ./
COPY jdk8/java.security /usr/local/openjdk-8/jre/lib/security/java.security

VOLUME /var/log/fdserver

CMD [ "./boot.sh" ]

HEALTHCHECK --interval=2s --timeout=60s --start-period=10s --retries=3 CMD [ "./health-check.sh" ]
